// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/habits/data/models/habit_event_model.dart';
import 'features/habits/data/models/habit_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4443944137001311041),
    name: 'HabitEventModel',
    lastPropertyId: const obx_int.IdUid(9, 7559968223015650280),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4320939354905747529),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5458876746953566256),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 121040704723485622),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4903019618210379376),
        name: 'habitId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 187418499156174257),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8626893269511659187),
        name: 'date',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(3, 2810567381276528018),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2650626907311982424),
        name: 'statusName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1827279718481185495),
        name: 'countValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5159373252535424841),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 596049222678343672),
        name: 'failReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7559968223015650280),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5633362972816185087),
    name: 'HabitModel',
    lastPropertyId: const obx_int.IdUid(14, 1522494561595009745),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5309852812447479408),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6685651465137661324),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 8356015126913473897),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 471247928406699492),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3983562215818606155),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3316216496683764914),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 112987177943081283),
        name: 'categoryName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5832905624556446633),
        name: 'scheduleJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3796132052733049862),
        name: 'goalJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5336973053706830883),
        name: 'difficulty',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6425793703391035001),
        name: 'strictnessName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 9099338222813511088),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4597155276903632219),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6046603199123125546),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1522494561595009745),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5633362972816185087),
    lastIndexId: const obx_int.IdUid(4, 8356015126913473897),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    HabitEventModel: obx_int.EntityDefinition<HabitEventModel>(
      model: _entities[0],
      toOneRelations: (HabitEventModel object) => [],
      toManyRelations: (HabitEventModel object) => {},
      getId: (HabitEventModel object) => object.dbId,
      setId: (HabitEventModel object, int id) {
        object.dbId = id;
      },
      objectToFB: (HabitEventModel object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final habitIdOffset = fbb.writeString(object.habitId);
        final statusNameOffset = fbb.writeString(object.statusName);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        final failReasonOffset = object.failReason == null
            ? null
            : fbb.writeString(object.failReason!);
        fbb.startTable(10);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, habitIdOffset);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addOffset(4, statusNameOffset);
        fbb.addInt64(5, object.countValue);
        fbb.addOffset(6, noteOffset);
        fbb.addOffset(7, failReasonOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = HabitEventModel()
          ..dbId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..habitId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          )
          ..statusName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..countValue = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..note = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16)
          ..failReason = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 18)
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          );

        return object;
      },
    ),
    HabitModel: obx_int.EntityDefinition<HabitModel>(
      model: _entities[1],
      toOneRelations: (HabitModel object) => [],
      toManyRelations: (HabitModel object) => {},
      getId: (HabitModel object) => object.dbId,
      setId: (HabitModel object, int id) {
        object.dbId = id;
      },
      objectToFB: (HabitModel object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        final colorOffset = fbb.writeString(object.color);
        final categoryNameOffset = fbb.writeString(object.categoryName);
        final scheduleJsonOffset = fbb.writeString(object.scheduleJson);
        final goalJsonOffset = fbb.writeString(object.goalJson);
        final strictnessNameOffset = fbb.writeString(object.strictnessName);
        fbb.startTable(15);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, iconOffset);
        fbb.addOffset(4, colorOffset);
        fbb.addOffset(5, categoryNameOffset);
        fbb.addOffset(6, scheduleJsonOffset);
        fbb.addOffset(7, goalJsonOffset);
        fbb.addInt64(8, object.difficulty);
        fbb.addOffset(9, strictnessNameOffset);
        fbb.addInt64(10, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(11, object.endDate?.millisecondsSinceEpoch);
        fbb.addBool(12, object.isActive);
        fbb.addInt64(13, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final object = HabitModel()
          ..dbId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..icon = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..color = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..categoryName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..scheduleJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..goalJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..difficulty = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..strictnessName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..startDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
          )
          ..endDate = endDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endDateValue)
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0),
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HabitEventModel] entity fields to define ObjectBox queries.
class HabitEventModel_ {
  /// See [HabitEventModel.dbId].
  static final dbId = obx.QueryIntegerProperty<HabitEventModel>(
    _entities[0].properties[0],
  );

  /// See [HabitEventModel.id].
  static final id = obx.QueryStringProperty<HabitEventModel>(
    _entities[0].properties[1],
  );

  /// See [HabitEventModel.habitId].
  static final habitId = obx.QueryStringProperty<HabitEventModel>(
    _entities[0].properties[2],
  );

  /// See [HabitEventModel.date].
  static final date = obx.QueryDateProperty<HabitEventModel>(
    _entities[0].properties[3],
  );

  /// See [HabitEventModel.statusName].
  static final statusName = obx.QueryStringProperty<HabitEventModel>(
    _entities[0].properties[4],
  );

  /// See [HabitEventModel.countValue].
  static final countValue = obx.QueryIntegerProperty<HabitEventModel>(
    _entities[0].properties[5],
  );

  /// See [HabitEventModel.note].
  static final note = obx.QueryStringProperty<HabitEventModel>(
    _entities[0].properties[6],
  );

  /// See [HabitEventModel.failReason].
  static final failReason = obx.QueryStringProperty<HabitEventModel>(
    _entities[0].properties[7],
  );

  /// See [HabitEventModel.createdAt].
  static final createdAt = obx.QueryDateProperty<HabitEventModel>(
    _entities[0].properties[8],
  );
}

/// [HabitModel] entity fields to define ObjectBox queries.
class HabitModel_ {
  /// See [HabitModel.dbId].
  static final dbId = obx.QueryIntegerProperty<HabitModel>(
    _entities[1].properties[0],
  );

  /// See [HabitModel.id].
  static final id = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[1],
  );

  /// See [HabitModel.name].
  static final name = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[2],
  );

  /// See [HabitModel.icon].
  static final icon = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[3],
  );

  /// See [HabitModel.color].
  static final color = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[4],
  );

  /// See [HabitModel.categoryName].
  static final categoryName = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[5],
  );

  /// See [HabitModel.scheduleJson].
  static final scheduleJson = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[6],
  );

  /// See [HabitModel.goalJson].
  static final goalJson = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[7],
  );

  /// See [HabitModel.difficulty].
  static final difficulty = obx.QueryIntegerProperty<HabitModel>(
    _entities[1].properties[8],
  );

  /// See [HabitModel.strictnessName].
  static final strictnessName = obx.QueryStringProperty<HabitModel>(
    _entities[1].properties[9],
  );

  /// See [HabitModel.startDate].
  static final startDate = obx.QueryDateProperty<HabitModel>(
    _entities[1].properties[10],
  );

  /// See [HabitModel.endDate].
  static final endDate = obx.QueryDateProperty<HabitModel>(
    _entities[1].properties[11],
  );

  /// See [HabitModel.isActive].
  static final isActive = obx.QueryBooleanProperty<HabitModel>(
    _entities[1].properties[12],
  );

  /// See [HabitModel.createdAt].
  static final createdAt = obx.QueryDateProperty<HabitModel>(
    _entities[1].properties[13],
  );
}
